//
//  Default configuration values for Timepix
//
#ifndef TIMEPIXCONFIGDEFAULTS_HH
#define TIMEPIXCONFIGDEFAULTS_HH

#define TIMEPIX_DAC_IKRUM_DEFAULT       5
#define TIMEPIX_DAC_DISC_DEFAULT        127
#define TIMEPIX_DAC_PREAMP_DEFAULT      255
#define TIMEPIX_DAC_BUFANALOGA_DEFAULT  127
#define TIMEPIX_DAC_BUFANALOGB_DEFAULT  127
#define TIMEPIX_DAC_HIST_DEFAULT        0
#define TIMEPIX_DAC_THLFINE_DEFAULT     250
#define TIMEPIX_DAC_THLCOURSE_DEFAULT   7
#define TIMEPIX_DAC_VCAS_DEFAULT        130
#define TIMEPIX_DAC_FBK_DEFAULT         128
#define TIMEPIX_DAC_GND_DEFAULT         80
#define TIMEPIX_DAC_THS_DEFAULT         85
#define TIMEPIX_DAC_BIASLVDS_DEFAULT    235
#define TIMEPIX_DAC_REFLVDS_DEFAULT     235

#define TIMEPIX_DAC_BIAS_DEFAULT        100
#define TIMEPIX_FLAGS_DEFAULT           0

#endif
