tgtnames := control_gui catest

tgtsrcs_control_gui := control.cc 
tgtsrcs_control_gui += MainWindow.cc      MainWindow_moc.cc
tgtsrcs_control_gui += ConfigSelect.cc    ConfigSelect_moc.cc
tgtsrcs_control_gui += NodeSelect.cc      NodeSelect_moc.cc
tgtsrcs_control_gui += SelectDialog.cc    SelectDialog_moc.cc
tgtsrcs_control_gui += PartitionSelect.cc PartitionSelect_moc.cc
tgtsrcs_control_gui += StateSelect.cc     StateSelect_moc.cc
tgtsrcs_control_gui += PVDisplay.cc       PVDisplay_moc.cc
tgtsrcs_control_gui += SeqAppliance.cc
tgtsrcs_control_gui += PVManager.cc
tgtsrcs_control_gui += PVMonitor.cc
tgtsrcs_control_gui += PVControl.cc
tgtsrcs_control_gui += EpicsCA.cc
tgtlibs_control_gui := pdsdata/xtcdata pdsdata/opal1kdata pdsdata/pulnixdata pdsdata/camdata pdsdata/evrdata pdsdata/acqdata pdsdata/controldata
tgtlibs_control_gui += pds/service pds/collection pds/xtc pds/mon pds/vmon pds/utility pds/client pds/config pds/management
tgtlibs_control_gui += pdsapp/configdb
tgtlibs_control_gui += qt/QtGui qt/QtCore
tgtlibs_control_gui += epics/ca epics/Com
tgtslib_control_gui := /usr/lib/rt
tgtincs_control_gui := qt/include
tgtincs_control_gui += epics/include epics/include/os/Linux

tgtsrcs_catest := catest.cc PVMonitor.cc EpicsCA.cc
tgtslib_catest := /usr/lib/rt
tgtincs_catest := epics/include epics/include/os/Linux
tgtlibs_catest := epics/ca epics/Com
tgtlibs_catest += pdsdata/controldata pdsdata/xtcdata
tgtlibs_catest += pds/service pds/mon pds/vmon pds/collection pds/xtc pds/utility pds/config